steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/containers/.m2
      - .
  - name: gcr.io/cloud-builders/mvn
    args:
      - install
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -rn
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/containers
